---

- name: Add vagrant user to docker group.
  user:
    name: vagrant
    groups: docker
    append: true

- name: Install Pip.
  apt:
    name: python3-pip
    state: present

- name: Install Docker Python library.
  pip:
    name: docker
    state: present
