---

- name: Install Bastion
  hosts: [localhost]
  gather_facts: false
  #connection: local

  vars_files:
    ../vars/main.yml

  tasks:
    - include_tasks: ~/ingot-ansible/roles/common/tasks/fw_bastion.yml
    - include_tasks: ~/ingot-ansible/roles/common/tasks/fw_all.yml


    
