---

- name: "Install Bastion"
  hosts: [localhost]
  gather_facts: true
  #connection: local

  vars_files:
    ../vars/main.yml

  tasks:
    - include_tasks: fw_bastion.yml
    - include_tasks: fw_all.yml


    
