---
# These tasks install http and the php modules.

- name: "Update and Dist Upgrade Server Packages"
  become: true
  apt:
    name: dist
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
  register: dist_upgrade


- name: "Installation install software properties commons"
  becomes: true
  apt:
    name: {{ item }}
    state: present
  with_items:
    - software-properties-common
    - ca-certificates
      - apt-transport-https
      - lsb-release
      - build-essential
      - net-tools
      - curl
      - mysql-client-8.0
      - unzip
      - libssl-dev
  update_cache: true
  cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"

- name: "Update Packages"
  become: true
  apt: 
    name:
    update_cache: yes


- name: "Install http and php etc"
  become: true
  apt:
    name:
      - apache2
      - apache2-utils
      - lynx
    state: latest
    update_cache: true
  notify: restart-apache

# Adding PHP Repository
- name: "Add Repo PHP 8.1"
  become: true
  apt_repository:
    repo: ppa:ondrej/php
    state: present

# PHP Main Package Installations
- name: "Installation of PHP -V"
  become: true
  apt:
    name:
      - php{{ php_version }}
      - libapache2-mod-php
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
  register: PHP_8

# Debug PHP version Number
- name: Debug Installation of PHP -V
  debug: var=PHP_8.stdout_lines

- name: Install PHP Extensions
  become: true
  apt:
    name:
      - php{{ php_version }}-fpm
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-cgi
      - php{{ php_version }}-cli
      - php{{ php_version }}-common
      - php{{ php_version }}-curl
      - php{{ php_version }}-gd
      - php{{ php_version }}-http
      - php{{ php_version }}-intl
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-soap
      - php{{ php_version }}-mysql
      - php{{ php_version }}-bz2
      - php{{ php_version }}-opcache
      - php{{ php_version }}-iconv
      - php{{ php_version }}-ftp
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
  notify:
    - reload-fpm

- name: "insert iptables rule for httpd"
  become: true
  lineinfile:
    dest: /etc/sysconfig/iptables
    create: yes
    state: present
    regexp: "{{ httpd_port }}"
    insertafter: "^:OUTPUT "
    line: "-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart-iptables

- name: "http service state"
  service:
    name: apache2
    state: started
    enabled: yes
