---

- name: "Create System User"
  become: true
  become_user: sudo
  user:
    name: "{{ ubuntu_user }}"
    append: true
    shell: /bin/bash
    system: false
    create_home: true
    home: /home/{{ ubuntu_user }}
#shell: /usr/sbin/nologin
